### ISSUE TITLE
Jolie on Windows - ant test

### ISSUE THREAD

**Issue by mwallnoefer** [jolie/jolie#68]
On Windows during testing SSL I sporadically encountered:

```
 [exec] Nov 05, 2015 6:29:52 PM jolie.Interpreter logSevere
 [exec] SCHWERWIEGEND: [http_post.ol] Request-Response process for test threw an undeclared fault for that operation (IOException), throwing TypeMismatch
 [exec] Nov 05, 2015 6:29:52 PM jolie.Interpreter logWarning
 [exec] WARNUNG: [http_server.ol] java.nio.channels.ClosedChannelException
 [exec]     at java.nio.channels.spi.AbstractSelectableChannel.configureBlocking(Unknown Source)
 [exec]     at jolie.net.CommCore$SelectorThread.register(CommCore.java:886)

 [exec]     at jolie.net.CommCore.registerForSelection(CommCore.java:938)
 [exec]     at jolie.net.SelectableStreamingCommChannel._disposeForInputImpl(SelectableStreamingCommChannel.java:108)
 [exec]     at jolie.net.SelectableStreamingCommChannel.disposeForInputImpl(SelectableStreamingCommChannel.java:117)
 [exec]     at jolie.net.CommChannel.disposeForInput(CommChannel.java:303)
 [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.handleDirectMessage(CommCore.java:559)
 [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.handleMessage(CommCore.java:572)
 [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.run(CommCore.java:606)
 [exec]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 [exec]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 [exec]     at java.lang.Thread.run(Unknown Source)
 [exec]
 [exec] Nov 05, 2015 6:29:52 PM jolie.Interpreter logInfo
 [exec] INFORMATION: [http_post.ol] jolie.net.ChannelClosingException: [http] Remote host closed connection.
 [exec]     at jolie.net.http.HttpParser.parseRequest(HttpParser.java:176)
 [exec]     at jolie.net.http.HttpParser.parseMessageType(HttpParser.java:208)
 [exec]     at jolie.net.http.HttpParser.parse(HttpParser.java:358)
 [exec]     at jolie.net.HttpProtocol.recv_internal(HttpProtocol.java:1235)
 [exec]     at jolie.net.http.HttpUtils.recv(HttpUtils.java:129)
 [exec]     at jolie.net.HttpProtocol.recv(HttpProtocol.java:1350)
 [exec]     at jolie.net.SocketCommChannel.recvImpl(SocketCommChannel.java:95)
 [exec]     at jolie.net.CommChannel.recv(CommChannel.java:198)
 [exec]     at jolie.net.AbstractCommChannel$ResponseReceiver.run(AbstractCommChannel.java:227)
 [exec]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 [exec]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 [exec]     at java.lang.Thread.run(Unknown Source)
 [exec]
 [exec] Nov 05, 2015 6:29:52 PM jolie.Interpreter logSevere
 [exec] SCHWERWIEGEND: [http_server.ol] java.nio.channels.AsynchronousCloseException
 [exec]     at java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source)
 [exec]     at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
 [exec]     at java.nio.channels.Channels.writeFullyImpl(Unknown Source)
 [exec]     at java.nio.channels.Channels.writeFully(Unknown Source)
 [exec]     at java.nio.channels.Channels.access$000(Unknown Source)
 [exec]     at java.nio.channels.Channels$1.write(Unknown Source)
 [exec]     at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
 [exec]     at java.io.BufferedOutputStream.flush(Unknown Source)
 [exec]     at jolie.net.SocketCommChannel.sendImpl(SocketCommChannel.java:112)
 [exec]     at jolie.net.SelectableStreamingCommChannel._send(SelectableStreamingCommChannel.java:101)
 [exec]     at jolie.net.SelectableStreamingCommChannel.send(SelectableStreamingCommChannel.java:78)
 [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.handleDirectMessage(CommCore.java:541)
 [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.handleMessage(CommCore.java:572)
 [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.run(CommCore.java:606)
 [exec]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 [exec]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 [exec]     at java.lang.Thread.run(Unknown Source)
 [exec]
 [exec] Nov 05, 2015 6:29:52 PM jolie.Interpreter logInfo
 [exec] INFORMATION: [test.ol] Internal server error
 [exec] http_post.ol...
```

**Comment by fmontesi** [comment]
Should be fixed now.

**Comment by mwallnoefer** [comment]
Will test it when I get a moment.

**Comment by mwallnoefer** [comment]
Unfortunately not yet fixed:

     [exec] WARNUNG: [sodep_server.ol] java.nio.channels.ClosedChannelException
     [exec]     at java.nio.channels.spi.AbstractSelectableChannel.configureBlocking(Unknown Source)
     [exec]     at jolie.net.CommCore$SelectorThread.register(CommCore.java:888)
     [exec]     at jolie.net.CommCore.registerForSelection(CommCore.java:940)
     [exec]     at jolie.net.SelectableStreamingCommChannel._disposeForInputImpl(SelectableStreamingCommChannel.java:108)
     [exec]     at jolie.net.SelectableStreamingCommChannel.disposeForInputImpl(SelectableStreamingCommChannel.java:117)
     [exec]     at jolie.net.CommChannel.disposeForInput(CommChannel.java:303)
     [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.handleDirectMessage(CommCore.java:559)
     [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.handleMessage(CommCore.java:572)
     [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.run(CommCore.java:606)
     [exec]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
     [exec]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
     [exec]     at java.lang.Thread.run(Unknown Source)
     [exec]
     [exec] Nov 21, 2015 3:41:40 PM jolie.Interpreter logSevere
     [exec] SCHWERWIEGEND: [sodep_server.ol] java.nio.channels.ClosedChannelException
     [exec]     at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(Unknown Source)
     [exec]     at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
     [exec]     at java.nio.channels.Channels.writeFullyImpl(Unknown Source)
     [exec]     at java.nio.channels.Channels.writeFully(Unknown Source)
     [exec]     at java.nio.channels.Channels.access$000(Unknown Source)
     [exec]     at java.nio.channels.Channels$1.write(Unknown Source)
     [exec]     at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
     [exec]     at java.io.BufferedOutputStream.flush(Unknown Source)
     [exec]     at jolie.net.SocketCommChannel.sendImpl(SocketCommChannel.java:112)
     [exec]     at jolie.net.SelectableStreamingCommChannel._send(SelectableStreamingCommChannel.java:101)
     [exec]     at jolie.net.SelectableStreamingCommChannel.send(SelectableStreamingCommChannel.java:78)
     [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.handleDirectMessage(CommCore.java:541)
     [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.handleMessage(CommCore.java:572)
     [exec]     at jolie.net.CommCore$CommChannelHandlerRunnable.run(CommCore.java:606)
     [exec]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
     [exec]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
     [exec]     at java.lang.Thread.run(Unknown Source)
     [exec]
     [exec] Nov 21, 2015 3:41:41 PM jolie.Interpreter logSevere
     [exec] SCHWERWIEGEND: [server.ol] Request-Response process for test threw an undeclared fault for that operation (IOException), throwing TypeMismatch
     [exec] Nov 21, 2015 3:41:41 PM jolie.Interpreter logInfo
     [exec] INFORMATION: [server.ol] java.io.EOFException
     [exec]     at java.io.DataInputStream.readFully(Unknown Source)
     [exec]     at java.io.DataInputStream.readLong(Unknown Source)
     [exec]     at jolie.net.SodepProtocol.readMessage(SodepProtocol.java:249)
     [exec]     at jolie.net.SodepProtocol.recv(SodepProtocol.java:290)
     [exec]     at jolie.net.SocketCommChannel.recvImpl(SocketCommChannel.java:95)
     [exec]     at jolie.net.CommChannel.recv(CommChannel.java:198)
     [exec]     at jolie.net.AbstractCommChannel$ResponseReceiver.run(AbstractCommChannel.java:227)
     [exec]     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
     [exec]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
     [exec]     at java.lang.Thread.run(Unknown Source)
     [exec]
     [exec] Nov 21, 2015 3:41:41 PM jolie.Interpreter logInfo
     [exec] INFORMATION: [test.ol] Internal server error
     [exec] server.ol...

**Comment by mwallnoefer** [comment]
Yeah, it is only reproducible on "master" and it not failing always. "java8" seems fine to me.

**Comment by mwallnoefer** [comment]
@fmontesi Any news on this?

**Comment by fmontesi** [comment]
Not yet. I am working on a remake of CommCore with other people here at the
University of Southern Denmark, which will introduce many fixes in general
to communications. I'll keep you posted as soon as we have something that
looks stable.

**Comment by mwallnoefer** [comment]
I think we should close this, since in the meantime the Java 8-based Jolie interpreter became the mainstream version.
If I manage to reproduce it I will reopen!
